### ISSUE TITLE
openTSDB python driver

### ISSUE THREAD

**Issue by ipmstyle** [jeonghoonkang/BerePi#14]
https://github.com/scarchik/opentsdb-py
https://pypi.org/project/opentsdb-py/

openTSDB python 라이브러리로 opentsdb-py 를 추천하는 것 같습니다.
테스트해보는 것도 좋을 것 같습니다.

그대로 사용하거나 브랜치 따서 수정하는 것도 좋을 것 같습니다.

**Comment by jeonghoonkang** [comment]
기본 드라이버 사용 가능
