### ISSUE TITLE
mongodb python driver

### ISSUE THREAD

**Issue by jeonghoonkang** [jeonghoonkang/BerePi#19]
<pre>

>>> d = datetime.datetime(2009, 11, 12, 12)
>>> for post in posts.find({"date": {"$lt": d}}).sort("author"):
...   print post
...
{u'date': datetime.datetime(2009, 11, 10, 10, 45), u'text': u'and pretty easy too!', u'_id': ObjectId('...'), u'author': u'Eliot', u'title': u'MongoDB is fun'}
{u'date': datetime.datetime(2009, 11, 12, 11, 14), u'text': u'Another post!', u'_id': ObjectId('...'), u'author': u'Mike', u'tags': [u'bulk', u'insert']}
&lt 연산자가 쿼리의 범위를 제한
sort()가 author에 따라 순서대로 정렬

index를 date, author 
explain() 메소드 

>>> posts.find({"date": {"$lt": d}}).sort("author").explain()["cursor"]
u'BasicCursor'

>>> posts.find({"date": {"$lt": d}}).sort("author").explain()["nscanned"]
3

>>> from pymongo import ASCENDING, DESCENDING >>> posts.create_index([("date", DESCENDING), ("author", ASCENDING)]) u'date_-1_author_1' 

>>> posts.find({"date": {"$lt": d}}).sort("author").explain()["cursor"] u'BtreeCursor date_-1_author_1' >>> posts.find({"date": {"$lt": d}}).sort("author").explain()["nscanned"] 2

</pre>

**Comment by ChulseoungChae** [comment]
### Mongodb python driver 구조 및 구동시간

 - 기본적으로 300대의 차량을 loop돌며 한차량씩 MongoDB에서 조건 sql문으로 쿼리 요청

  - ![그림1](https://user-images.githubusercontent.com/39073918/65143965-305b3280-da51-11e9-836c-ffb0ad0c5665.png)


    ① mongoDB로 쿼리요청을 하는데 걸리는 시간
    ② query 요청의 결과값으로 반환된 cursor가 루프돌며 데이터를 빈 리스트에 한line씩 추가하는데 걸리는 시간
    ③ 빈리스트에 추가된 데이터를 데이터프레임으로 변환 후 NaN값 처리후 파일로 변환하는데 걸리는 시간

  - 쿼리 요청하는 collection에 저장된 총 데이터 line(row)수 : 135,805,167 line (column : 34)
  - 코드 테스트 서버 : 125.140.110.217 -p 7777 (64242서버)
  - 약 cursor가 200만 line정도 데이터를 받아오는데 약 700초정도 소요됨
  - 그리고 한 line(row)씩 딕셔너리 형태로 이루어진 list를 데이터 프레임으로 만들고 파일로 만드는 시간이 제일 오래 걸림


추가로 mongoDB에서 openTSDB로 데이터를 옮기는코드 실행중
- 코드 실행 서버 : 125.140.110.217 -p 7776 (54242서버)
- 코드위치 : [Link](https://github.com/ChulseoungChae/Universal_code/tree/master/MongoToTSDB)
- 추후 shell script로 사용자 인자값을 전달받도록 수정 예정

**Comment by jeonghoonkang** [comment]
![image](https://user-images.githubusercontent.com/4180063/65146870-d1e58280-da57-11e9-840d-9b988e515c14.png)

**Comment by KimHyeongGoo** [comment]
- ![run1](https://user-images.githubusercontent.com/53587555/65157888-6b1e9400-da6c-11e9-8152-6b3d87c75110.PNG)

- ![run2](https://user-images.githubusercontent.com/53587555/65157902-707bde80-da6c-11e9-9fb1-616cebd6111a.PNG)

**Comment by jeonghoonkang** [comment]
아이고.. 처음에 CSV 로 만들었으면, 5시간이면 다 다운 받았을것을.
자자.. 이제 점점 더 흥미로워진다. ㅎㅎㅎ
잘 업그레이드 해 보자
