### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ipmstyle** [jeonghoonkang/BerePi#21]
<img width="134" alt="fail2ban_list_result" src="https://user-images.githubusercontent.com/4587330/210972256-8eab6bba-3813-42d5-8fc9-4d9043f111a1.png">

![IOTstack_main_menu_01](https://user-images.githubusercontent.com/4587330/211264293-50299f86-7bd9-48c1-a7f7-c36c471b35fa.png)

![IOTstack_select_wireguard](https://user-images.githubusercontent.com/4587330/211264295-7b7cfe6f-ea8d-417c-828a-f90c4f95f2e2.png)

![IOTstack_PC_client_01](https://user-images.githubusercontent.com/4587330/211313165-e919cb7d-c47d-409a-b43f-63728887c577.png)

![IOTstack_PC_client_02](https://user-images.githubusercontent.com/4587330/211313732-189aea07-9de7-407d-b75b-bb2d9938a29f.png)

![IOTstack_PC_client_activate](https://user-images.githubusercontent.com/4587330/211313754-e21758ca-5f01-4d0b-90df-0e2a669530ee.png)

![OpenLog_to_RasPi](https://user-images.githubusercontent.com/4587330/213354776-15a24575-7202-44db-be2b-a65b826e6e16.png)

**Comment by jeonghoonkang** [comment]
추후 검토 close
